# Generated by Django 4.2.7 on 2026-09-21 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loja', '0006_carrinho_carrinhoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorito', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('favorito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='loja.favorito')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favoritos', to='loja.produto')),
            ],
        ),
    ]
